### ISSUE TITLE
Hardware/AVR/GPIO.h Arduino header

### ISSUE THREAD

**Issue by paulalting** [mikaelpatel/Arduino-GPIO#7]
I use Eclipse Sloeber IDE and opening up file 'Hardware/AVR/GPIO.h' I noticed some unresolved symbols and functions at lines 36, 39, 170, 175 and 211.

To fix, I placed '#include "Arduino.h" so it will resolve symbols.
Am I correct in thinking that this include should be included ?

Many thanks for your work on great code.
Paul - VK7KPA

**Comment by mikaelpatel** [comment]
@paulalting Thanks for your interest in this project. You are correct about the implicit include of the Arduino.h header file. An explicit include is needed when the Arduino IDE and build system are not used. I guess this issue is really about supporting other build systems and IDEs. I will consider adding the include to the necessary source files. Thanks for your feedback and above all testing this library.
